export interface TrekPackage {
  id: string;
  name: string;
  image?: string;
  duration: string;
  altitude: string;
  difficulty: string;
  idealFor: string;
  summary: string;
  pricing: { label: string; price: string }[];
  itinerary: string[];
  includes: string[];
  excludes: string[];
}

export const trekPackages: TrekPackage[] = [
  {
    id: "langtang-valley",
    name: "Langtang Valley Trek",
    duration: "8 Days",
    altitude: "Up to 5,033m",
    difficulty: "Easy/Moderate",
    idealFor: "First-time trekkers",
    summary:
      "A shorter and comfortable introduction to Himalayan trekking with gradual altitude gain.",
    pricing: [
      { label: "2-4 Pax", price: "$900 / person" },
      { label: "4-7 Pax", price: "$850 / person" },
      { label: "7-10 Pax", price: "$825 / person" },
    ],
    itinerary: [
      "Day 1: Kathmandu to Syabrubesi (1,550m) - 7-8 hour drive by private or shared jeep.",
      "Day 2: Syabrubesi to Lama Hotel (2,470m) - Trek through lush river forests.",
      "Day 3: Lama Hotel to Langtang Village (3,430m) - Langtang Lirung views begin to open.",
      "Day 4: Langtang Village to Kyanjin Gompa (3,870m) - Reach the glacial bowl and visit yak cheese factory.",
      "Day 5: Kyanjin Gompa exploration (up to 5,033m) - Hike to Tserko Ri or Kyanjin Ri (4,773m).",
      "Day 6: Kyanjin Gompa to Lama Hotel (2,470m) - Retrace route with mostly downhill trekking.",
      "Day 7: Lama Hotel to Syabrubesi (1,550m) - Final full day of walking.",
      "Day 8: Syabrubesi to Kathmandu (1,400m) - Drive back to the city.",
    ],
    includes: [
      "Airport pickup and drop",
      "Licensed trekking guide",
      "Tea house accommodation during trek",
      "Daily breakfast on trekking days",
      "Basic first aid support",
    ],
    excludes: [
      "International flights",
      "Travel insurance",
      "Lunch and dinner in Kathmandu",
      "Personal gear and tips",
    ],
  },
  {
    id: "annapurna-circuit",
    name: "Annapurna Base Camp Trek",
    duration: "14 Days",
    altitude: "Up to 4,130m",
    difficulty: "Moderate",
    idealFor: "Intermediate trekkers",
    summary:
      "A complete Annapurna sanctuary journey with Poon Hill sunrise, Gurung villages, forest trails, and a full ascent to Annapurna Base Camp.",
    pricing: [
      { label: "1 Pax", price: "$1,400" },
      { label: "2-4 Pax", price: "$1,350 / person" },
      { label: "4+ Pax", price: "$1,200 / person" },
    ],
    itinerary: [
      "Day 1: Arrival in Kathmandu - Airport pick-up and hotel check-in.",
      "Day 2: Kathmandu sightseeing - Trek briefing and permit preparation.",
      "Day 3: Kathmandu to Pokhara - 6-7 hour tourist bus or 25-minute flight.",
      "Day 4: Pokhara to Tikhedhunga - 1.5 hour drive and around 4 hour trek (staircase day).",
      "Day 5: Tikhedhunga to Ghorepani - Steep climb through rhododendron forests.",
      "Day 6: Poon Hill sunrise to Tadapani - Morning viewpoint at 3,210m then trek onward.",
      "Day 7: Tadapani to Chhomrong - Descend to river and climb to the Gurung village.",
      "Day 8: Chhomrong to Dovan - Enter the deep sanctuary valley.",
      "Day 9: Dovan to Deurali - Pass Hinku Cave as high-altitude vegetation begins.",
      "Day 10: Deurali to Annapurna Base Camp - Reach ABC (4,130m) via Machhapuchhre Base Camp.",
      "Day 11: ABC to Bamboo - Long descent back down the valley.",
      "Day 12: Bamboo to Jhinu - Relax in natural riverside hot springs.",
      "Day 13: Jhinu to Pokhara - Walk to road-head and take around 3-hour jeep drive.",
      "Day 14: Pokhara to Kathmandu - Return to the capital by bus or flight.",
    ],
    includes: [
      "All required trekking permits",
      "Guide + porter support",
      "Tea house accommodation",
      "Breakfast, lunch, and dinner during trek",
      "Ground transportation as per itinerary",
    ],
    excludes: [
      "Visa fees",
      "Personal travel insurance",
      "Personal expenses and hot showers",
      "Emergency evacuation costs",
    ],
  },
  {
    id: "everest-base-camp",
    name: "Everest Base Camp Trek",
    duration: "16+ Days",
    altitude: "Up to 5,500m+",
    difficulty: "Mod/Challenging",
    idealFor: "Experienced trekkers",
    summary:
      "High-altitude expedition-style itinerary with stronger logistics and support for advanced routes.",
    pricing: [
      { label: "1 Pax", price: "$2,240" },
      { label: "2-4 Pax", price: "$1,990 / person" },
      { label: "5+ Pax", price: "$1,950 / person" },
    ],
    itinerary: [
      "Day 1: Arrive in Kathmandu, expedition briefing, and detailed gear inspection.",
      "Day 2: Fly to Lukla and trek to Phakding on a short introductory trail day.",
      "Day 3: Trek from Phakding to Namche Bazaar through suspension bridges and pine forest.",
      "Day 4: Acclimatization day at Namche with a hike to higher viewpoints and return.",
      "Day 5: Trek to Tengboche with panoramic views of Ama Dablam and nearby ridgelines.",
      "Day 6: Continue to Dingboche through alpine terrain and increasingly dry high-valley climate.",
      "Day 7: Acclimatization day in Dingboche with controlled elevation gain on side trails.",
      "Day 8: Trek to Lobuche following memorial ridge and glacial moraine paths.",
      "Day 9: Trek to Gorak Shep and continue to Everest Base Camp before returning to lodge.",
      "Day 10: Early hike to Kala Patthar for sunrise panorama, then descend to Pheriche.",
      "Day 11: Trek to Namche Bazaar on a long descent with meal and hydration breaks.",
      "Day 12: Trek to Lukla and complete final evening with support crew.",
      "Day 13: Fly back to Kathmandu and transfer to hotel for recovery.",
      "Day 14: Contingency day in case of flight weather delays in Lukla sector.",
      "Day 15: Optional sightseeing or rest day in Kathmandu with equipment return.",
      "Day 16: Departure transfer to international airport.",
    ],
    includes: [
      "Senior mountain guide + full support crew",
      "Permits and logistics management",
      "All meals during trek",
      "Accommodation as per route plan",
      "Emergency oxygen and first response kit",
    ],
    excludes: [
      "International airfare and visa",
      "Comprehensive evacuation insurance",
      "Personal mountaineering equipment rental",
      "Tips for crew and guide team",
    ],
  },
  {
    id: "poon-hill",
    name: "Poon Hill Trek",
    duration: "8 Days",
    altitude: "Up to 3,210m",
    difficulty: "Easy/Moderate",
    idealFor: "Beginners + short trek seekers",
    summary:
      "A short Annapurna trek featuring Poon Hill sunrise, rhododendron forests, and authentic Gurung village culture.",
    pricing: [
      { label: "1 Pax", price: "$799" },
      { label: "2-4 Pax", price: "$750 / person" },
      { label: "4+ Pax", price: "$700 / person" },
    ],
    itinerary: [
      "Day 1: Arrive in Kathmandu - Airport pickup and hotel check-in.",
      "Day 2: Kathmandu sightseeing - Trek briefing and permit preparation.",
      "Day 3: Kathmandu to Pokhara - Drive or short flight transfer.",
      "Day 4: Pokhara to Ulleri - 2.5 hour drive to Hile and around 3 hour trek with stone staircase ascent.",
      "Day 5: Ulleri to Ghorepani - Trek through dense rhododendron forest trails.",
      "Day 6: Poon Hill sunrise to Tadapani - Early viewpoint hike at 3,210m, then continue trek.",
      "Day 7: Tadapani to Ghandruk - Descend to the Gurung village and local museum area.",
      "Day 8: Ghandruk to Pokhara to Kathmandu - Walk to Nayapul, drive to Pokhara, then transfer to Kathmandu.",
    ],
    includes: [
      "Airport pickup and drop",
      "ACAP + TIMS permits",
      "Guide support during trek",
      "Tea house accommodation on route",
      "Ground transportation as per itinerary",
    ],
    excludes: [
      "International flights and visa",
      "Travel insurance",
      "Personal expenses and beverages",
      "Tips and personal trekking gear",
    ],
  },
  {
    id: "upper-mustang",
    name: "Upper Mustang Trek",
    duration: "12 Days",
    altitude: "Up to 4,200m",
    difficulty: "Moderate",
    idealFor: "Culture + landscape trekkers",
    summary:
      "A 12-day Upper Mustang journey with Lo Manthang, red cliffs, monasteries, and restricted-area logistics professionally managed.",
    pricing: [
      { label: "2-4 Pax", price: "$2,299 / person" },
      { label: "4-7 Pax", price: "$2,250 / person" },
      { label: "7-10 Pax", price: "$2,150 / person" },
    ],
    itinerary: [
      "Day 1: Kathmandu - Arrival and permit processing.",
      "Day 2: Kathmandu to Pokhara - Drive or flight to the lake city.",
      "Day 3: Pokhara to Jomsom to Kagbeni - 20-minute flight and around 3-hour trek; entry to Upper Mustang.",
      "Day 4: Kagbeni to Chele - Enter the restricted zone where RAP daily permit counting starts.",
      "Day 5: Chele to Syangboche - Cross high passes with wide Himalayan views.",
      "Day 6: Syangboche to Lo Manthang - Arrive at the historic walled capital.",
      "Day 7: Explore Lo Manthang - Visit Chhoser caves and key monasteries.",
      "Day 8: Lo Manthang to Dhakmar - Scenic descent with the iconic red cliffs.",
      "Day 9: Dhakmar to Ghiling - Walk through ancient monasteries and local culture routes.",
      "Day 10: Ghiling to Muktinath - Exit restricted zone and continue by trek/drive to the temple area.",
      "Day 11: Muktinath to Jomsom - Morning temple darshan and bath, then return to Jomsom.",
      "Day 12: Jomsom to Pokhara to Kathmandu - Fly back and connect for onward departure.",
    ],
    includes: [
      "Upper Mustang restricted permits",
      "ACAP permit and logistics",
      "Guide + porter support",
      "Accommodation and meals during trek",
      "Domestic route transport as per itinerary",
    ],
    excludes: [
      "International flights and visa",
      "Travel insurance and evacuation cover",
      "Personal expenses and beverages",
      "Tips and personal trekking gear",
    ],
  },
  {
    id: "annapurna-semi-circuit",
    name: "Annapurna Semi-Circuit Trek",
    duration: "10 Days",
    altitude: "Up to 5,416m",
    difficulty: "Moderate/Challenging",
    idealFor: "Trekkers seeking Thorong La in a shorter itinerary",
    summary:
      "A compact Annapurna Semi-Circuit route from Dharapani to Muktinath via Thorong La Pass with acclimatization in Manang and strong value logistics.",
    pricing: [
      { label: "1-2 Pax", price: "$975 / person" },
      { label: "2-4 Pax", price: "$965 / person" },
      { label: "4+ Pax", price: "$950 / person" },
    ],
    itinerary: [
      "Day 1: Drive Kathmandu to Besishahar to Dharapani (1,860m) - 9-10 hours drive.",
      "Day 2: Trek Dharapani to Chame (2,670m) - 5-6 hours.",
      "Day 3: Trek Chame to Upper Pisang (3,300m) - 5-6 hours.",
      "Day 4: Trek Upper Pisang to Ngawal to Manang (3,540m) - 7-8 hours.",
      "Day 5: Rest day in Manang - Acclimatization and optional Gangapurna Lake side hike.",
      "Day 6: Trek Manang to Yak Kharka to Ledar (4,200m) - 4-5 hours.",
      "Day 7: Trek Ledar to Thorong Phedi or High Camp (4,800m) - 3-4 hours.",
      "Day 8: Cross Thorong La Pass (5,416m) and descend to Muktinath (3,800m) - 8-9 hours.",
      "Day 9: Drive Muktinath to Jomsom to Pokhara (820m) - 8-9 hours drive.",
      "Day 10: Drive or fly Pokhara to Kathmandu.",
    ],
    includes: [
      "ACAP + TIMS permits",
      "Licensed guide and porter support (shared basis)",
      "9 nights tea house accommodation",
      "3 meals per day during trekking days",
      "Kathmandu-Besishahar-Dharapani ground transport",
      "Muktinath-Jomsom-Pokhara ground transport",
      "Staff insurance, snacks, and office administration",
    ],
    excludes: [
      "International flights and Nepal visa",
      "Personal travel insurance",
      "Personal expenses, drinks, and hot showers",
      "Pokhara-Kathmandu flight fare if flight option is chosen",
      "Tips and personal trekking gear",
    ],
  },
  {
    id: "nar-phu-valley-jomsom",
    name: "Nar Phu Valley to Jomsom Trek",
    duration: "14 Days",
    altitude: "Up to 5,416m",
    difficulty: "Challenging",
    idealFor: "Experienced trekkers wanting a restricted-area route",
    summary:
      "A remote Nar Phu Valley crossing via Kang La and Thorong La, combining restricted Tibetan-influenced villages with a full exit to Jomsom.",
    pricing: [
      { label: "1-2 Pax", price: "$1,999 / person" },
      { label: "2-4 Pax", price: "$1,900 / person" },
      { label: "4+ Pax", price: "$1,850 / person" },
    ],
    itinerary: [
      "Day 1: Drive Kathmandu to Besisahar to Dharapani (1,860m).",
      "Day 2: Trek Dharapani to Koto (2,600m).",
      "Day 3: Enter restricted area and trek Koto to Meta (3,560m).",
      "Day 4: Trek Meta to Phu Village (4,080m).",
      "Day 5: Exploration day in Phu - Visit Tashi Lhakhang Monastery.",
      "Day 6: Trek Phu to Nar Phedi (3,490m) and stay at monastery.",
      "Day 7: Trek Nar Phedi to Nar Village (4,110m).",
      "Day 8: Trek Nar to Kang La Pass (5,320m) to Ngawal (3,650m).",
      "Day 9: Trek Ngawal to Manang (3,540m).",
      "Day 10: Trek Manang to Yak Kharka (4,050m).",
      "Day 11: Trek Yak Kharka to Thorong Phedi (4,450m).",
      "Day 12: Cross Thorong La Pass (5,416m) to Muktinath (3,800m).",
      "Day 13: Drive Muktinath to Jomsom and fly or drive to Pokhara.",
      "Day 14: Drive or fly Pokhara to Kathmandu.",
    ],
    includes: [
      "Nar Phu restricted area permit",
      "ACAP + TIMS permits",
      "Licensed guide and porter support (shared basis)",
      "13 nights tea house or monastery accommodation",
      "3 meals per day during the trek",
      "Kathmandu-Besisahar-Dharapani jeep transport",
      "Muktinath-Jomsom jeep transport",
      "Jomsom-Pokhara flight or drive transfer arrangement",
      "Staff insurance, logistics, and office administration",
    ],
    excludes: [
      "International flights and Nepal visa",
      "Personal travel insurance",
      "Personal expenses, drinks, charging, and hot showers",
      "Costs due to weather delays and route changes",
      "Tips and personal trekking gear",
    ],
  },
  {
    id: "sacred-valley-ruby-valley",
    name: "Sacred Valley & Ruby Valley Exploration",
    duration: "15 Days",
    altitude: "Up to 4,200m",
    difficulty: "Moderate/Challenging",
    idealFor: "Trekkers seeking remote culture and monastery routes",
    summary:
      "A 15-day Tsum Valley and Ganesh Himal route featuring sacred monasteries, Mu Gompa high valley exploration, and Ruby Valley-style mountain wilderness.",
    pricing: [
      { label: "1-2 Pax", price: "$1,500 / person" },
      { label: "2-4 Pax", price: "$1,400 / person" },
      { label: "4+ Pax", price: "$1,350 / person" },
    ],
    itinerary: [
      "Day 1: Drive Kathmandu to Arughat to Machha Khola (930m).",
      "Day 2: Trek Machha Khola to Jagat (1,340m).",
      "Day 3: Trek Jagat to Lokpa (2,240m) and enter Tsum Valley.",
      "Day 4: Trek Lokpa to Chumling (2,386m).",
      "Day 5: Trek Chumling to Chhekamparo (3,010m).",
      "Day 6: Trek Chhekamparo to Nile (3,360m).",
      "Day 7: Trek Nile to Mu Gompa (3,700m) and explore the high valley.",
      "Day 8: Trek Mu Gompa to Rachen Gompa (3,240m).",
      "Day 9: Trek Rachen Gompa to Gumba Lungdang (3,200m) - Ganesh Himal base area.",
      "Day 10: Hike to Ganesh Himal Base Camp (4,200m) and return to Gumba Lungdang.",
      "Day 11: Trek Gumba Lungdang to Lokpa (2,240m).",
      "Day 12: Trek Lokpa to Philim (1,570m).",
      "Day 13: Trek Philim to Khorlabesi (970m).",
      "Day 14: Trek Khorlabesi to Soti Khola (700m).",
      "Day 15: Drive Soti Khola to Kathmandu.",
    ],
    includes: [
      "Tsum Valley restricted area permit",
      "MCAP + TIMS permits",
      "Licensed guide and porter support (shared basis)",
      "14 nights tea house or monastery accommodation",
      "3 meals per day during the trek",
      "Kathmandu-Machha Khola shared jeep transport",
      "Soti Khola-Kathmandu shared jeep transport",
      "Staff insurance, logistics, and emergency first-aid kit",
    ],
    excludes: [
      "International flights and Nepal visa",
      "Personal travel insurance",
      "Personal expenses, drinks, charging, and hot showers",
      "Costs due to weather or road/landslide delays",
      "Tips and personal trekking gear",
    ],
  },
  {
    id: "lower-dolpo-trek",
    name: "Lower Dolpo Trek",
    duration: "18 Days",
    altitude: "Up to 5,309m",
    difficulty: "Challenging",
    idealFor: "Experienced trekkers seeking remote high-pass expeditions",
    summary:
      "A full Lower Dolpo traverse with flights to Juphal, Dho Tarap acclimatization, twin high passes (Numa La and Baga La), and Phoksundo Lake exploration.",
    pricing: [
      { label: "1-2 Pax", price: "$2,525 / person" },
      { label: "2-4 Pax", price: "$2,475 / person" },
      { label: "4+ Pax", price: "$2,450 / person" },
    ],
    itinerary: [
      "Day 1: Arrival in Kathmandu (1,350m).",
      "Day 2: Permit preparation and briefing.",
      "Day 3: Fly Kathmandu to Nepalgunj.",
      "Day 4: Fly Nepalgunj to Juphal (2,475m) and trek to Dunai.",
      "Day 5: Trek Dunai to Tarakot (2,540m).",
      "Day 6: Trek Tarakot to Laina Odar (3,370m).",
      "Day 7: Trek Laina Odar to Nawarpani (3,475m).",
      "Day 8: Trek Nawarpani to Dho Tarap (3,945m).",
      "Day 9: Rest and acclimatization in Dho Tarap with monastery visits.",
      "Day 10: Trek Dho Tarap to Numa La Base Camp (4,440m).",
      "Day 11: Cross Numa La Pass (5,309m) to Pelung Tang (4,465m).",
      "Day 12: Cross Baga La Pass (5,170m) to Dajok Tang (4,080m).",
      "Day 13: Trek Dajok Tang to Phoksundo Lake (3,610m).",
      "Day 14: Rest at Phoksundo Lake and visit Ringmo Village.",
      "Day 15: Trek Phoksundo to Chhepka (2,830m).",
      "Day 16: Trek Chhepka to Juphal.",
      "Day 17: Fly Juphal to Nepalgunj and Kathmandu.",
      "Day 18: Kathmandu departure.",
    ],
    includes: [
      "Round-trip domestic flights: Kathmandu-Nepalgunj-Juphal",
      "Lower Dolpo restricted permit and Shey Phoksundo National Park permit",
      "Experienced licensed guide and porter support (shared basis)",
      "Tea house and tent accommodation as per route",
      "3 meals per day during the trek",
      "Logistics cargo handling, Nepalgunj hotel, and airport transfers",
      "Staff insurance, emergency kit, and office operations",
    ],
    excludes: [
      "International flights and Nepal visa",
      "Personal travel insurance and evacuation cover",
      "Personal expenses, beverages, charging, and hot showers",
      "Costs due to weather-related flight delays",
      "Tips and personal trekking gear",
    ],
  },
  {
    id: "everest-gokyo-cho-la",
    name: "Everest Base Camp via Gokyo Lakes & Cho La Pass Trek",
    duration: "16 Days",
    altitude: "Up to 5,550m",
    difficulty: "Challenging",
    idealFor: "High-altitude trekkers wanting a full Everest circuit",
    summary:
      "A complete Khumbu high-pass route linking Gokyo Lakes, Cho La Pass, Everest Base Camp, and Kala Patthar with structured acclimatization and a built-in flight buffer.",
    pricing: [
      { label: "1-2 Pax", price: "$2,100 / person" },
      { label: "2-4 Pax", price: "$2,050 / person" },
      { label: "4+ Pax", price: "$2,000 / person" },
    ],
    itinerary: [
      "Day 1: Arrival in Kathmandu and trek briefing.",
      "Day 2: Fly Kathmandu or Ramechhap to Lukla (2,840m) and trek to Phakding.",
      "Day 3: Trek Phakding to Namche Bazaar (3,440m).",
      "Day 4: Acclimatization in Namche with hike to Everest View Hotel.",
      "Day 5: Trek Namche to Dole (4,110m).",
      "Day 6: Trek Dole to Machhermo (4,470m).",
      "Day 7: Trek Machhermo to Gokyo Lakes (4,800m).",
      "Day 8: Sunrise at Gokyo Ri (5,357m), then trek to Dragnag (4,700m).",
      "Day 9: Cross Cho La Pass (5,420m) and trek to Dzongla (4,830m).",
      "Day 10: Trek Dzongla to Lobuche (4,910m).",
      "Day 11: Trek to Everest Base Camp (5,364m) and overnight at Gorak Shep.",
      "Day 12: Sunrise at Kala Patthar (5,550m), then descend to Pheriche.",
      "Day 13: Trek Pheriche to Namche Bazaar.",
      "Day 14: Trek Namche to Lukla.",
      "Day 15: Fly Lukla to Kathmandu or Ramechhap.",
      "Day 16: Buffer day for Lukla flight delays or departure.",
    ],
    includes: [
      "Round-trip domestic Lukla flights (Kathmandu or Ramechhap sector)",
      "Khumbu Pasang Lhamu permit and Sagarmatha National Park permit",
      "Senior high-pass guide and porter support (shared basis)",
      "14 nights tea house accommodation",
      "3 meals per day during the trek",
      "Airport transfers, staff insurance, and first-aid or oxygen support",
      "Route logistics and trekking operation management",
    ],
    excludes: [
      "International flights and Nepal visa",
      "Personal travel insurance and emergency evacuation",
      "Personal expenses, beverages, charging, and hot showers",
      "Costs due to weather-related flight delays",
      "Tips and personal trekking gear",
    ],
  },
].sort((a, b) => a.name.localeCompare(b.name));

export const trekPackagesById = Object.fromEntries(
  trekPackages.map((pkg) => [pkg.id, pkg]),
) as Record<string, TrekPackage>;
